version: "3.9"

services:
  redis:
    image: "redis:alpine"
    container_name: magrit-redis
    privileged: true
    command: sh -c "sysctl vm.overcommit_memory=1 && redis-server /home/redis.conf"
    volumes:
      - ./redis/conf:/home
    networks:
       - app-network
    sysctls:
        net.core.somaxconn: 512

  nginx:
    container_name: magrit-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - magritapp
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - staticfiles:/var/www/static
      - ./nginx/conf-https:/etc/nginx/sites-enabled
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - magritapp

  magritapp:
    container_name: magrit-app
    build:
      context: ../..
      dockerfile: misc/Docker/app/Dockerfile
    links:
      - redis
    networks:
      - app-network
    volumes:
      - staticfiles:/home/app/magrit/magrit_app/static
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge

volumes:
  staticfiles:
